apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: app
spec:
  selector:
    app.kubernetes.io/name: MyApp
  type: ExternalName
  externalName: exam.jamcity.com
  ports:
    - protocol: TCP
      port: 80
      targetPort: 15017